name: Windows Build and Release

on: 
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
    
      - name: Install Node and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Electron Builder Action
        uses: samuelmeuli/action-electron-builder@v1.3.0
        with:
          build_script_name: electron-pack
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
